### ISSUE TITLE
잘못된 jwt 보냈을 시 서버에러 발생

### ISSUE THREAD

**Issue by SeungYongChoi** [RETURN-TO-SOJU/Mongle-Backend#16]
현재 jwt가 잘못되면 500번 에러가 발생 -> 400번대 에러로 수정 요함

**Comment by YOONSEOUNGHWAN** [comment]
에러 컨트롤 하는 법이 익숙하지 않습니다. 알려주십쇼!!
추가로, 알려주시기 전까지 Error코드 숙지해오겠습니다.

**Comment by YOONSEOUNGHWAN** [comment]
<img width="503" alt="image" src="https://user-images.githubusercontent.com/78069223/184287772-1d939d14-f37e-4cb2-90f7-fb5526c7e753.png">
