### ISSUE TITLE
OauthService 리펙토링 요청

### ISSUE THREAD

**Issue by SeungYongChoi** [RETURN-TO-SOJU/Mongle-Backend#17]
현재 카카오 정보를 가져온 후 이미 존재하는 회원이면 에러를 던지는데 에러를 던지기보다는 
회원의 kakaoToken정보 + 닉네임을 업데이트 하는것이 더 좋을 것 같음

getUserProfileByToken의 메소드명은 토큰으로 유저의 프로필 정보를 가져온다는 의미로 해석이 되는데
실제 로직은 getUserAttributesByToken로 가져온 카카오 유저 정보를 기반으로 새로운 user 엔티티를 만드는 행위를 함
메소드 명 변경하면 더 좋을것 같음 
또한 해당 메소드 내에 유저 정보를 매핑하는 코드
```
    Map<String, Object> userAttributesByToken = getUserAttributesByToken(kakaoTokenDto);
        KakaoUserInfo kakaoUserInfo = new KakaoUserInfo(userAttributesByToken);
        Long kakao_id = kakaoUserInfo.getId();
        String name = kakaoUserInfo.getName();
        String nickName = kakaoUserInfo.getNickName();
```
이 코드를 따로 메소드로 빼면 다른곳에서 코드 재사용하기가 용이하지 않을까 싶음
ex)따로 메소드로 뺐을 경우, 카카오 파일 S3에 올릴 때 닉네임 정보를 재요청하는데 이 때 사용가능함

현재 확장성을 위해 path variable로 provider를 받는데 정확히 kakao라고 명시해두는 것이 조금 더 좋을것 같음
(확장한다 해도 kakao, google, naver 등 몇개 없기 때문에 따로 api를 직접 만들어 주는것이 더 명확할것같음,
또한 kakao와 google은 서로 다른 곳으로 호출을 보내기 때문에(지금 코드를 예시로 들면 getUserAttributesByToken메소드는 카카오에게만 보내는 메소드) path variable로 한다면 if문으로 분기처리가 필요하다고 느껴짐 차라리 api를 분리하여 if문과 같은 분기 없이 정해진 메소드를 실행하는게 더 가독성이 좋을것 같음)

**Comment by YOONSEOUNGHWAN** [comment]
기존 Spring Security OAuth를 의존하면, proivder를 기준으로 정해진 형식의 REST API 요청을 할 수 있었기에 초기에 그렇게 작성했습니다.

하지만 Android와 연동하는 현재 서비스에선(Android에서Oauth2Library를 의존) 불필요하다고 생각합니다. 반영 후 , Close하겠습니다.

**Comment by YOONSEOUNGHWAN** [comment]
getUserProfileByToken에서는 회원가입 및 로그인 절차를 수행해야 함으로 함수명을 바꾸겠습니다.

재사용 성을 고려했을 때, 다음과 같이 수정했습니다.
```java
private KakaoUserInfo getKakaoUserInfo(KakaoTokenDto kakaoTokenDto) {
        Map<String, Object> userAttributesByToken = getUserAttributesByToken(kakaoTokenDto);
        KakaoUserInfo kakaoUserInfo = new KakaoUserInfo(userAttributesByToken);
        return kakaoUserInfo;
    }
```

**Comment by YOONSEOUNGHWAN** [comment]
기존 존재하는 회원인 경우, update하는  방향으로 설정 했으며, 함수명을 바꿨습니다.

Token과 함께 이뤄지는 메소드이기에, With와 By중 고민을 많이 했으나.. 
with로 했는데.. 차이를 잘 모르겠습니다.

피드백 부탁드립니다.

```java
private User createAndUpdateKakaoUserProfileWithToken(String providerName, KakaoTokenDto kakaoTokenDto){
        if(!providerName.equals("kakao")){
            throw new IllegalArgumentException("잘못된 접근입니다.");
        }
        KakaoUserInfo kakaoUserInfo = getKakaoUserInfoWithToken(kakaoTokenDto);
        Long kakao_id = kakaoUserInfo.getId();
        String name = kakaoUserInfo.getName();
        String nickName = kakaoUserInfo.getNickName();
        Optional<User> optionalUser = userRepository.findById(kakao_id);
        if(optionalUser.isPresent()){
            User existUser = optionalUser.get();
            existUser.updateNickName(nickName);
            existUser.updateKakaoToken(kakaoTokenDto);
            return existUser;
        }
        User user = new User(kakao_id, name, nickName, kakaoTokenDto.getAccessToken(), kakaoTokenDto.getRefreshToken(), Role.ROLE_USER);
        User save = userRepository.save(user);
        return save;
    }
```

**Comment by SeungYongChoi** [comment]
함수명에서 with랑 by의 차이점은 단어 자체에 있다고 생각합니다. 
with는 ~~와 함께, by는 ~~에 의해서 즉 이 메소드에서는 토큰과 함께 or 토큰에 의해서 둘 중 더 어울리는것으로 채택하면 좋을 것이라고
개인적으로 생각합니다.

다만 함수명보다 현재 코드에서는 if문 다음에 else문으로 감싸지 않아서 존재하는 회원일 경우에 업데이트 하고 또 새로운 유저를 만들게 될 것 같습니다. 
지금 로직으로는 유저가 이미 가입되어 있는 상황에서 pk값이 중복되어 DB에 저장될 수 없다는 에러를 뱉을 것 같습니다.
코드에 다음과 같이 else문을 추가하는게 좋을 것 같습니다. (댓글 작성칸에서 바로 코드를 작성하다보니 이쁘게 작성이 안되네요..ㅎㅎ)

```
private User createAndUpdateKakaoUserProfileWithToken(KakaoTokenDto kakaoTokenDto){
        KakaoUserInfo kakaoUserInfo = getKakaoUserInfoWithToken(kakaoTokenDto);
        Long kakao_id = kakaoUserInfo.getId();
        String name = kakaoUserInfo.getName();
        String nickName = kakaoUserInfo.getNickName();
        Optional<User> optionalUser = userRepository.findById(kakao_id);
        if(optionalUser.isPresent()){
            User existUser = optionalUser.get();
            existUser.updateNickName(nickName);
            existUser.updateKakaoAccessToken(kakaoTokenDto.getAccessToken());
            existUser.updateKakaoRefreshToken(kakaoTokenDto.getRefreshToken());
            return existUser;
        }else{
        User user = new User(kakao_id, name, nickName, kakaoTokenDto.getAccessToken(), kakaoTokenDto.getRefreshToken(), Role.ROLE_USER);
        User save = userRepository.save(user);
        return save;
        }
    }
```

**Comment by YOONSEOUNGHWAN** [comment]
지금 로직에서 유저가 이미 가입되어 있는 상황에서는 pk값을 따로 저장하지는 않습니다.
update NickName, accesstoken, refreshtoken만을 갱신하고 있습니다.
또한, if문은 return처리 되기에 하위 로직이 실행되는 것은 해당 유저가 존재하지 않을 경우이기에 close하겠습니다!!
