### ISSUE TITLE
Exception 네이밍

### ISSUE THREAD

**Issue by YOONSEOUNGHWAN** [RETURN-TO-SOJU/Mongle-Backend#26]
```java
NotFoundUserException.class,
UserNotFoundByIdException.class
```

현재 우리 서비스는 user를 찾을때,
Id, nickname, email...등등의 조건으로 찾을 수 있음.
하지만, 닉네임의 경우 겹치는 경우가 너무 많을 수도 있고, email로 유저를 찾는 경우는 없을 것이라 생각이 됨.

따라서, 유저를 찾는 로직은 PK값으로 제한이 될 수도 있고, 아닐 수도 있을 텐데
이를 하나의 Exception인 NotFound로 가는건 어떨지...? @SeungYongChoi

**Comment by SeungYongChoi** [comment]
몽글몽글 서비스에서 유저를 찾는 로직이 id밖에 없을 것 같다는 생각이 들어 찬성입니다.
다만 나중에 유저를 찾는 로직이 id를 제외하고 또 생긴다면 그 상황에서는
1. exception을 새로 만들어서 분리
2. error를 던질 때 message로 설명하기 
둘 중 하나로 선택하면 좋을 것 같습니다.

**Comment by YOONSEOUNGHWAN** [comment]
네 그럼 NotFound로 우선 가겠습니다
