### ISSUE TITLE
로그인 시, 카카오 토큰 재발급

### ISSUE THREAD

**Issue by YOONSEOUNGHWAN** [RETURN-TO-SOJU/Mongle-Backend#27]
```java

    /**
     * 로그인 요청시마다 client가 귀찮을 수도 있으니, 기존 refresh로 access 만료되면 받아서 사용하기
     */
    @PostMapping("/renew/kakao")
    public String renewAccessToken(@RequestBody String token){
        KakaoTokenDto kakaoTokenDto = oauthService.renewKakaoToken(token);
        return kakaoTokenDto.getAccessToken();
    }
```

해당 uri로 접근해서 사용하면 됩니다
body
raw
{refreshToken}

**잠시만 사용하고 지울 예정**

확인하면 close 부탁합니다.

**Comment by SeungYongChoi** [comment]
refreshtoken만 바디에 실어서 보내면 되나요?
리턴 값은 accessToken만 받아오는 건가요?

**Comment by YOONSEOUNGHWAN** [comment]
넵, 카카오톡 재발급 로직에서는 user의 accessToken값이 필요하지 않기에, refreshToken만 실어서 보내주면 됩니다.

return 값은
accessToken & refreshToken 둘 다 받아옵니다.
<img width="833" alt="image" src="https://user-images.githubusercontent.com/78069223/184347606-c6cd7f68-8b13-474f-8ff7-9fd537523fa0.png">
카카오 RESTAPI 정책에 의하면 refreshToken은  1개월 미만인 경우에만 선택적으로 재발급해주기에

발급받은 경우 : 새 refreshToken은 응답으로 줌.
발급받지 못한 경우 : 기존 refreshToken을 응답으로 줌.

**Comment by YOONSEOUNGHWAN** [comment]
생각과 다르게 코드를 짰었네요,, 잠시 쓰고 버릴 api라서 죄송합니다.

```java
@Data
public class ReissueTokenRequestDto {
    private String accessToken;
    private String refreshToken;
}
```

요청시에는 해당 dto를 참고해주세요

**Comment by SeungYongChoi** [comment]
네 확인했습니다. 
덕분에 편하게 요청할 수 있겠네요 감사합니다 ㅎㅎ
