### ISSUE TITLE
카카오ML데이터 처리후 DB저장시 Calender 엔티티를 모든 데이터마다 찾아오는 이슈 

### ISSUE THREAD

**Issue by SeungYongChoi** [RETURN-TO-SOJU/Mongle-Backend#34]
분석된 발화문을 저장할 때 DailySentence 엔티티에 저장됩니다.
이 엔티티는 캘린더(특정 요일) 엔티티를 속성으로 가지고 있어 DailySentence 엔티티를 만들때마다 
해당 userId와 날짜에 해당하는 캘린더 엔티티를 디비에서 찾아와야합니다. 

디비에서 찾아오는 로직이 캘린더 엔티티의 pk값으로 찾아오는 것이 아니라 
userId와 LocalDate로 찾아오는 로직이라 영속성컨텍스트에 있음에도 불구하고 캐시를 활용하지 못하고 매번 디비에 쿼리가 나갑니다.
이를 해결할 좋은 방법이 있다면 알고 배우고 싶습니다.

**Comment by YOONSEOUNGHWAN** [comment]
**모든 쿼리 탐색문에서 em.find()를 호출하는 경우를 제외하면 JPQL이 실행됩니다.**

따라서 영속성 컨텍스트에 있는 entity를 조회하는 경우는 pk값을 통한 쿼리에서만 캐싱된 데이터를 가져오는 것이고,

DATA JPA에서는 findById()를 제외한 모든 쿼리에서 select절이 호출 된다고 보면 될 것 같습니다.

추후 QueryDSL을 사용할 경우, QueryDSL은 JPQL Mapper 역할을 하는 것이기 때문에, 무조건 쿼리가 한 번 더 나간다고 보면 될 것 같습니다.

<img width="461" alt="image" src="https://user-images.githubusercontent.com/78069223/185186261-47408200-985c-466f-b289-ef158fcea067.png">

**Comment by YOONSEOUNGHWAN** [comment]
해결할 방법.
영속성 컨텍스트는 한 transaction 내에서만 존재하기 때문에,

```java
public void saveKakaoMLData(KakaoMLDataSaveRequestDto dto) {
        Long userId = dto.getUserId();
        List<KakaoMLData> datas = dto.getData();

        User user = userRepository.findById(userId).orElseThrow(NotFoundUserException::new);

        // 매번 calender를 찾는 쿼리문이 나감,,, 수정할 방법을 찾고싶은데 모르겠다..
        datas.stream()
                .forEach(data -> {
                    String time = data.getTime();
                    LocalDateTime localDateTime = convertStringTimeToLocalDateTimeFormat(time);
                    Calender calender = this.findCalenderByUserAndLocalDate(user, localDateTime);

                    String sentence = data.getText();
                    Emotion emotion = data.getEmotion();
                    //todo Roomname, kakaoText 넣어줘야함
                    // 1. roomname 구현이 가능할진 모르겠음
                    // 2. kakaoText: 본문 파일을 알아야 당일 카톡보기를 구현햘 수 있음
                    // but 현재 이걸 어떻게 구현할지 논의해야
                    // 3. 사용자가 톡방을 한번 더 올렸을 때 중복검사 로직이 없음

                    DailySentence dailySentence = new DailySentence(calender, sentence, emotion);
                    dailySentenceRepository.save(dailySentence);
                });
    }
```

해당 코드의 로직에서, 
User의
```java
@OneToMany(mappedBy = "user")
    private List<Calender> calenderList = new ArrayList<>();

```

해당 속성을 맵핑해주는 메소드를 하나 만들고 
그 메소드를 이용하면 어떨까 합니다..
